name: space_cosmos_clock
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  speech_to_text: ^6.6.1
  flutter_colorpicker: ^1.0.3
  flutter_tts: ^3.8.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
